const markdownBlockTypes = [
  'paragraph',
  'atxHeading',
  'setextHeading',
  'htmlBlock',
  'bulletList',
  'orderedList',
  'listItem',
  'thematicBreak',
  'blockquote',
  'fencedBlockquote',
  'indentedCodeBlock',
  'fencedCodeBlock',
  'table',
  'tableRow',
  'tableHead',
  'tableBody',
];
